apiVersion: v1
kind: Service
metadata:
  name: apps-deployment-service #service name
  namespace: w255
spec:
  selector:
    app: apps-deployment
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer